### ISSUE TITLE
Lost Grid?

### ISSUE THREAD

**Issue by fallenpeace** [Meteor-Community-Packages/meteor-postcss#9]
I cant seem to get LOST to work with this package.

https://github.com/peterramsing/lost/wiki/Installation

**Comment by juliancwirko** [comment]
Hi, I'll check this out asap. I'll keep you posted.

**Comment by juliancwirko** [comment]
What exactly doesn't work? Because I have done a quick test and everything seems to be ok. 
My test is on Meteor 1.3-rc.2 and postcss package in version 1.0.0-rc.2 but in older version the core logic is the same so it should also work. Lost version is 6.7.2 and PostCss version is 5.0.19 What I test is:

``` css
.lost-demo {
    lost-column: 1/3;
}
```

my output:

``` css
.lost-demo {
  width: calc(99.99% * 1/3 - (30px - 30px * 1/3));
}

.lost-demo:nth-child(1n) {
  float: left;
  margin-right: 30px;
  clear: none;
}

.lost-demo:last-child {
  margin-right: 0;
}

.lost-demo:nth-child(3n) {
  margin-right: 0;
  float: right;
}

.lost-demo:nth-child(3n + 1) {
  clear: left;
}
```
